"""Turn a Kokoro .srt into a TypeScript cue array for the Remotion caption track.

Remotion renders in a browser, so it cannot read the SRT off disk at runtime; the cues are
compiled into the episode instead. Frames are computed at the project rate so a caption lands on
the same frame as the word (recipe §6.6).

  python tools/video/srt_to_ts.py video/voice/ep05/ep05.srt tools/video/remotion/src/episodes/ep05/captions.ts [FPS]
"""
import json
import re
import sys
from pathlib import Path


def seconds(stamp: str) -> float:
    h, m, rest = stamp.split(":")
    s, ms = rest.split(",")
    return int(h) * 3600 + int(m) * 60 + int(s) + int(ms) / 1000


def main() -> None:
    src, dst = Path(sys.argv[1]), Path(sys.argv[2])
    fps = int(sys.argv[3]) if len(sys.argv) > 3 else 60
    blocks = re.findall(r"\d+\n([\d:,]+) --> ([\d:,]+)\n(.+)", src.read_text(encoding="utf-8"))
    rows = [
        f"  {{ from: {round(seconds(a) * fps)}, to: {round(seconds(b) * fps)}, text: {json.dumps(text.strip())} }},"
        for a, b, text in blocks
    ]
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text(
        "// Generated by tools/video/srt_to_ts.py — do not edit by hand.\n"
        "// Regenerate after re-voicing the script.\n"
        "export type Cue = { from: number; to: number; text: string };\n\n"
        "export const CUES: Cue[] = [\n" + "\n".join(rows) + "\n];\n",
        encoding="utf-8",
    )
    print(f"{dst} — {len(rows)} cues at {fps} fps")


main()
