class_name ArenaSceneryData
extends Resource
## Animated scenery of one Legendary or Mythic Endless skin: mask, grade, light zones, set piece,
## light sweep, shooting stars and glow particles (owner feedback 2026-09-15, ADR-0014).
##
## Everything works *with* the painting: `mask` (tools/art/endless_scenery.py) marks the painting's
## own light sources (R), the regions that may move (G), the scenery weight (B: 0 on the floor,
## rising to 1 across the rim tolerance) and zone ids (A). `ArenaAmbience` puts
## `arena_scenery.gdshader` on the background with these values and spawns the particles. The floor
## only ever gets `floor_saturation` (luminance kept), so the playfield, telegraphs and enemies stay
## as readable as before (GDD §8) and the Wisp stays the brightest small object (GDD §9).
## Generated by tools/art/make_endless_skin_data.py; edit the table in endless_scenery.py.

## Signature animated moment. CORONA: rotating rays and periodic flares around a disc (an eclipse).
## SWIRL: slow rotation of the painted region around a centre (a galaxy, a portal).
enum PieceKind { NONE, CORONA, SWIRL }

## Zone ids 1..MAX_ZONES fit the mask alpha encoding (A = 255 - id * ZONE_ALPHA_STEP).
const MAX_ZONES: int = 7
const ZONE_ALPHA_STEP: int = 28
## Mask texture size written by the art pipeline.
const MASK_SIZE := Vector2i(471, 836)
## The floor may gain at most this much saturation, never brightness.
const MAX_FLOOR_SATURATION: float = 1.12

## RGBA scenery mask (see the class description).
@export var mask: Texture2D

@export_group("Grade")
## Scenery saturation and contrast multipliers (1 = unchanged).
@export_range(0.5, 2.0, 0.01) var scenery_saturation: float = 1.0
@export_range(0.5, 2.0, 0.01) var scenery_contrast: float = 1.0
## Scenery brightness multiplier.
@export_range(0.5, 1.5, 0.01) var scenery_exposure: float = 1.0
## Split-tone colour lifts: shadows and highlights pulled toward the skin's palette (amount 0-1).
@export var shadow_lift: Color = Color.WHITE
@export_range(0.0, 1.0, 0.01) var shadow_lift_amount: float = 0.0
@export var highlight_lift: Color = Color.WHITE
@export_range(0.0, 1.0, 0.01) var highlight_lift_amount: float = 0.0
## Floor saturation multiplier (luminance preserved), at most `MAX_FLOOR_SATURATION`.
@export_range(1.0, 1.2, 0.01) var floor_saturation: float = 1.0

@export_group("Zones")
## Lit / moving regions; index + 1 is the zone id in the mask alpha.
@export var zones: Array[ArenaSceneryZone] = []

@export_group("Set piece")
@export var piece_kind: PieceKind = PieceKind.NONE
## Centre in background UV; must lie outside the floor + rim tolerance.
@export var piece_center_uv: Vector2 = Vector2.ZERO
## CORONA: radius of the dark disc in px. SWIRL: radius of the rotating region in px.
@export_range(0.0, 600.0, 1.0) var piece_radius_px: float = 0.0
## CORONA: how far rays reach past the disc, in px.
@export_range(0.0, 600.0, 1.0) var piece_extent_px: float = 0.0
@export var piece_color: Color = Color.WHITE
## Ray light level (CORONA) or core glow level (SWIRL).
@export_range(0.0, 3.0, 0.01) var piece_strength: float = 0.0
## CORONA: number of rays and ray sharpness exponent.
@export_range(0, 64, 1) var piece_rays: int = 0
@export_range(1.0, 16.0, 0.1) var piece_ray_sharpness: float = 6.0
## CORONA: ray rotation in rad/s. SWIRL: rotation cycles per second.
@export_range(0.0, 2.0, 0.001) var piece_speed: float = 0.0
## SWIRL: rotation swing per cycle in radians (small, so the painting never smears).
@export_range(0.0, 1.0, 0.01) var piece_swirl_radians: float = 0.0
## CORONA flares: average seconds between flares (0 = none), lobe length px, half-width degrees,
## colour and peak level.
@export_range(0.0, 60.0, 0.1) var flare_interval: float = 0.0
@export_range(0.0, 400.0, 1.0) var flare_length_px: float = 0.0
@export_range(0.0, 45.0, 0.5) var flare_width_degrees: float = 10.0
@export var flare_color: Color = Color.WHITE
@export_range(0.0, 4.0, 0.01) var flare_boost: float = 0.0

@export_group("Light sweep")
## A soft band of light crossing the scenery (glints on metal, god rays), weighted per zone.
@export var sweep_color: Color = Color.WHITE
@export_range(0.0, 2.0, 0.01) var sweep_strength: float = 0.0
## Travel direction in degrees (0 = rightward, 90 = downward), band half-width px.
@export_range(-180.0, 180.0, 1.0) var sweep_angle_degrees: float = 0.0
@export_range(1.0, 400.0, 1.0) var sweep_width_px: float = 40.0
## Seconds per sweep cycle and the share of it the band is moving (the rest is rest).
@export_range(1.0, 60.0, 0.1) var sweep_period: float = 8.0
@export_range(0.05, 1.0, 0.01) var sweep_duty: float = 0.4

@export_group("Shooting stars")
## Region in background UV where streaks fly; must stay clear of the floor + rim tolerance.
@export var streak_region_uv: Rect2 = Rect2()
## Average seconds between streaks (0 = none), speed px/s, tail length px, core width px, life s.
@export_range(0.0, 60.0, 0.1) var streak_interval: float = 0.0
@export_range(0.0, 2000.0, 1.0) var streak_speed_px: float = 500.0
@export_range(0.0, 400.0, 1.0) var streak_length_px: float = 90.0
@export_range(0.5, 12.0, 0.1) var streak_width_px: float = 2.0
@export_range(0.1, 3.0, 0.01) var streak_duration: float = 0.5
## Heading range in degrees (x = min, y = max; 0 = rightward, 90 = downward).
@export var streak_angle_degrees: Vector2 = Vector2(20.0, 40.0)
@export var streak_color: Color = Color.WHITE
@export_range(0.0, 3.0, 0.01) var streak_strength: float = 1.0

@export_group("Particles")
@export var emitters: Array[ArenaParticleEmitter] = []


## Returns authoring failures: mask, zone count, floor grade, flash spacing, emitters. The floor
## keep-out of centres, regions and emission paths is checked by `EndlessCatalog.validate()`.
func validate() -> PackedStringArray:
	var failures := PackedStringArray()
	if mask == null:
		failures.append("scenery mask is missing")
	elif Vector2i(mask.get_size()) != MASK_SIZE:
		failures.append("scenery mask is %s, expected %s" % [Vector2i(mask.get_size()), MASK_SIZE])
	if zones.size() > MAX_ZONES:
		failures.append("%d scenery zones, at most %d" % [zones.size(), MAX_ZONES])
	if floor_saturation > MAX_FLOOR_SATURATION:
		failures.append("floor saturation %.2f above %.2f" % [floor_saturation, MAX_FLOOR_SATURATION])
	for zone: ArenaSceneryZone in zones:
		if zone == null:
			failures.append("empty scenery zone slot")
			continue
		failures.append_array(zone.validate())
	for emitter: ArenaParticleEmitter in emitters:
		if emitter == null:
			failures.append("empty particle emitter slot")
			continue
		failures.append_array(emitter.validate())
	if piece_kind != PieceKind.NONE and piece_radius_px <= 0.0:
		failures.append("set piece without a radius")
	if streak_interval > 0.0 and not streak_region_uv.has_area():
		failures.append("shooting stars without a region")
	return failures
