class_name ArenaSceneryZone
extends Resource
## One lit and/or moving region of an Endless skin's scenery mask (zone id = index + 1).
##
## The mask (`ArenaSceneryData.mask`) says *where*: R holds how strongly a pixel is one of the
## painting's own light sources, G how strongly it may distort, A which zone owns it. This resource
## says *how*: light colour and animation, and the distortion mode. `ArenaAmbience` turns the
## time-based parts (breathing, flicker, flares, colour cycling) into one shader value per zone per
## frame; the per-pixel parts (twinkle, travelling pulses, colour shift, distortion) run in
## `arena_scenery.gdshader`. Generated by tools/art/make_endless_skin_data.py; edit the table in
## tools/art/endless_scenery.py.

## How the painting under G moves. RIPPLE: water. SHIMMER: heat haze over fire and falling light.
## WAVE: aurora ribbons (vertical waving along x). ROIL: slow cloud and mist churn.
enum WarpMode { NONE, RIPPLE, SHIMMER, WAVE, ROIL }

## Readable name for docs and debugging.
@export var zone_name: String = ""

@export_group("Light")
## Light colour added over the emissive pixels.
@export var light_color: Color = Color.WHITE
## Second colour for colour cycling (`hue_cycle`) and the spatial colour shift (`color_shift`).
@export var light_alt_color: Color = Color.WHITE
## Base light level (0 = no light). Kept so the Wisp stays the brightest small object (GDD §9).
@export_range(0.0, 3.0, 0.01) var light_strength: float = 0.0
## Share of the level that breathes (sine), and its rate in Hz.
@export_range(0.0, 1.0, 0.01) var breathe: float = 0.0
@export_range(0.0, 4.0, 0.01) var breathe_hz: float = 0.15
## Share of the level that flickers (noise), and its rate in Hz.
@export_range(0.0, 1.0, 0.01) var flicker: float = 0.0
@export_range(0.0, 20.0, 0.1) var flicker_hz: float = 6.0
## Average seconds between flares (0 = none; the wait is randomised by
## `ArenaAmbience.FLARE_JITTER`), the level a flare adds, and its rise and fade in seconds.
@export_range(0.0, 60.0, 0.1) var flare_interval: float = 0.0
@export_range(0.0, 3.0, 0.01) var flare_boost: float = 0.0
@export_range(0.01, 3.0, 0.01) var flare_rise: float = 0.3
@export_range(0.05, 5.0, 0.01) var flare_fade: float = 1.2
## A flare that reads as lightning: shares the arena-wide `ArenaAmbience.MIN_FLASH_INTERVAL`.
@export var flare_is_flash: bool = false
## Share of the time-based cycle toward `light_alt_color`, and its rate in Hz.
@export_range(0.0, 1.0, 0.01) var hue_cycle: float = 0.0
@export_range(0.0, 2.0, 0.01) var hue_cycle_hz: float = 0.05
## Spatial colour shift toward `light_alt_color`: share, cycles across the canvas, drift in Hz.
@export_range(0.0, 1.0, 0.01) var color_shift: float = 0.0
@export_range(0.0, 40.0, 0.1) var color_shift_cycles: float = 2.0
@export_range(0.0, 2.0, 0.01) var color_shift_hz: float = 0.08
## Per-point sparkle of small lights (stars, glints): share and rate in Hz.
@export_range(0.0, 1.0, 0.01) var twinkle: float = 0.0
@export_range(0.0, 8.0, 0.01) var twinkle_hz: float = 1.0
## Pulses travelling along the canvas height (falls, seams): share, cycles, rate in Hz
## (positive moves down, negative up).
@export_range(0.0, 1.0, 0.01) var travel: float = 0.0
@export_range(0.0, 80.0, 0.1) var travel_cycles: float = 8.0
@export_range(-8.0, 8.0, 0.01) var travel_hz: float = 0.5
## How strongly the skin's light sweep (`ArenaSceneryData.sweep_strength`) lights this zone.
@export_range(0.0, 1.0, 0.01) var sweep_weight: float = 0.0

@export_group("Distortion")
## Distortion mode for the zone's G pixels.
@export var warp_mode: WarpMode = WarpMode.NONE
## Peak displacement in background pixels (small: the painting must stay readable).
@export_range(0.0, 12.0, 0.1) var warp_px: float = 0.0
## Distortion rate in Hz and spatial frequency in cycles per 1000 background pixels.
@export_range(0.0, 4.0, 0.01) var warp_hz: float = 0.1
@export_range(0.0, 40.0, 0.1) var warp_cycles: float = 4.0


## Whether the zone lights anything.
func has_light() -> bool:
	return light_strength > 0.0 or flare_boost > 0.0


## Returns authoring failures (flash spacing, distortion without amplitude).
func validate() -> PackedStringArray:
	var failures := PackedStringArray()
	if flare_is_flash and flare_interval < ArenaAmbience.MIN_FLASH_INTERVAL:
		failures.append("%s: a flash every %.1f s strobes (minimum %.1f s)" % [
			zone_name, flare_interval, ArenaAmbience.MIN_FLASH_INTERVAL,
		])
	if warp_mode != WarpMode.NONE and warp_px <= 0.0:
		failures.append("%s: distortion mode without amplitude" % zone_name)
	return failures
