class_name ArenaSkinData
extends Resource
## One purchasable Endless background. A skin changes only what the arena looks like.
##
## There is deliberately no floor polygon here: every skin paints its floor to the one shared
## template in `EndlessCatalog.floor_polygon` (ADR-0014), so a cosmetic can never change play.
## Generated by tools/art/make_endless_skin_data.py from the art manifest; edit the generator.

## Shop rarity. Sets the price band, the card label and the animated scenery level
## (Legendary: calm living touches, Mythic: rich set pieces, Simple and Rare: none).
enum Tier { SIMPLE, RARE, LEGENDARY, MYTHIC }

## Player-facing tier names, indexed by `Tier`.
const TIER_NAMES: PackedStringArray = ["SIMPLE", "RARE", "LEGENDARY", "MYTHIC"]

## Stable identifier stored in the save (`owned_arena_skins`, `equipped_arena_skin`).
@export var skin_id: StringName
## Player-facing arena name.
@export var display_name: String
## Short flavour text for the Shop.
@export_multiline var description: String
## Shop rarity (price band, card label, scenery level).
@export var tier: Tier = Tier.SIMPLE
## Full-bleed 941x1672 background painted to the floor template. A path, loaded only when a run
## starts (`load_background()`), so the catalog never holds all thirty full-size textures at once.
@export_file("*.png") var background_path: String
## Small copy of the background for Shop cards (tools/art/extract_endless.py).
@export var thumbnail: Texture2D
## Rift Points price; zero for the default skin.
@export_range(0, 100000, 1) var price: int = 0
## Card accent colour; use a Palette constant, never a raw literal.
@export var accent: Color = Color.WHITE
## Animated scenery over the painted art (`ArenaAmbience`); null below Legendary, required from it.
@export var scenery: ArenaSceneryData
## Stand-in art that must never ship; `EndlessCatalog.validate()` rejects it.
@export var placeholder: bool = false


## Loads the full-size background (cached by the ResourceLoader while something holds it).
func load_background() -> Texture2D:
	if background_path.is_empty() or not ResourceLoader.exists(background_path):
		return null
	return load(background_path) as Texture2D


## The player-facing tier name, e.g. "MYTHIC".
func get_tier_name() -> String:
	return TIER_NAMES[clampi(tier, 0, TIER_NAMES.size() - 1)]


## Returns authoring failures for this skin. `check_background` loads the full-size texture
## to check its size; pass false where that memory matters.
func validate(check_background: bool = true) -> PackedStringArray:
	var failures := PackedStringArray()
	if skin_id.is_empty():
		failures.append("skin id is empty")
	if display_name.is_empty():
		failures.append("display name is empty")
	if background_path.is_empty() or not ResourceLoader.exists(background_path):
		failures.append("background %s is missing" % background_path)
	elif check_background:
		var background: Texture2D = load_background()
		if background == null or Vector2i(background.get_size()) != EndlessCatalog.BACKGROUND_SIZE:
			failures.append("background is %s, expected %s" % [
				Vector2i(background.get_size()) if background != null else Vector2i.ZERO,
				EndlessCatalog.BACKGROUND_SIZE,
			])
	if thumbnail == null:
		failures.append("thumbnail is missing")
	if price < 0:
		failures.append("price is negative")
	if placeholder:
		failures.append("placeholder art must not ship")
	if scenery != null and tier < Tier.LEGENDARY:
		failures.append("animated scenery is reserved for Legendary and Mythic skins")
	elif scenery == null and tier >= Tier.LEGENDARY:
		failures.append("Legendary and Mythic skins need animated scenery")
	if scenery != null:
		for failure: String in scenery.validate():
			failures.append("scenery: %s" % failure)
	return failures
