class_name CharacterPoseSheet
extends Resource
## Where each painted pose of a whole-pose sprite character is drawn, so poses never jump or resize.
##
## A sprite pack paints every pose on one canvas, but it does not frame the figure identically in
## each picture: the silhouette drifts a few pixels between poses and one of them may be drawn
## smaller inside extra padding. This sheet carries, per pose, the drawing offset that puts that
## pose's silhouette back on the collision-centre anchor and the scale that keeps its apparent
## height constant.
##
## Generated by [code]tools/art/extract_playable_characters.py[/code] from the approved pack — hand
## edits are lost on the next run.

## Pose names, in pack order; they match the sprite animation names one to one.
@export var pose_names: PackedStringArray = PackedStringArray()
## Drawing offset per pose, in source pixels, applied before [member pose_scales].
@export var pose_offsets: PackedVector2Array = PackedVector2Array()
## How far each pose's painted silhouette sits from the canvas centre, in source pixels, as measured
## when the sheet was generated. Adding it to the pose's offset gives the drift the runtime still
## carries, which is what an anchor-stability check compares between poses.
@export var pose_drifts: PackedVector2Array = PackedVector2Array()
## Uniform scale per pose; 1.0 leaves the painting at its authored size.
@export var pose_scales: PackedFloat32Array = PackedFloat32Array()
## Side of the square canvas every pose is painted on, in pixels.
@export_range(16.0, 4096.0, 1.0) var frame_size: float = 512.0

var _index: Dictionary[StringName, int] = {}


## True when [param pose] has a row in this sheet.
func has_pose(pose: StringName) -> bool:
	return _rows().has(pose)


## Drawing offset of [param pose] in source pixels, zero for an unknown pose.
func get_offset(pose: StringName) -> Vector2:
	var row: int = _rows().get(pose, -1)
	return pose_offsets[row] if row >= 0 else Vector2.ZERO


## Uniform scale of [param pose], 1.0 for an unknown pose.
func get_scale(pose: StringName) -> float:
	var row: int = _rows().get(pose, -1)
	return pose_scales[row] if row >= 0 else 1.0


## Every pose name in pack order, for tests and fixtures.
func get_pose_names() -> Array[StringName]:
	var names: Array[StringName] = []
	for name: String in pose_names:
		names.append(StringName(name))
	return names


## Drift [param pose] still carries after its offset is applied, in source pixels: how far its
## silhouette lands from the anchor. Zero for a pose the sheet does not know.
func get_residual_drift(pose: StringName) -> Vector2:
	var row: int = _rows().get(pose, -1)
	if row < 0 or row >= pose_drifts.size():
		return Vector2.ZERO
	return pose_drifts[row] + pose_offsets[row]


## Largest distance between any two poses' residual drift, in source pixels: the biggest anchor jump
## a state change can produce.
func get_anchor_spread() -> float:
	var spread: float = 0.0
	var residuals := PackedVector2Array()
	for index: int in mini(pose_drifts.size(), pose_offsets.size()):
		residuals.append(pose_drifts[index] + pose_offsets[index])
	for a: Vector2 in residuals:
		for b: Vector2 in residuals:
			spread = maxf(spread, a.distance_to(b))
	return spread


## Largest difference in scale between any two poses.
func get_scale_spread() -> float:
	if pose_scales.is_empty():
		return 0.0
	var lowest: float = pose_scales[0]
	var highest: float = pose_scales[0]
	for value: float in pose_scales:
		lowest = minf(lowest, value)
		highest = maxf(highest, value)
	return highest - lowest


## Returns authoring failures so a sheet can be checked without opening the editor.
func validate() -> PackedStringArray:
	var failures := PackedStringArray()
	if pose_names.is_empty():
		failures.append("sheet has no poses")
	if (
		pose_offsets.size() != pose_names.size()
		or pose_scales.size() != pose_names.size()
		or pose_drifts.size() != pose_names.size()
	):
		failures.append("the pose columns have different lengths")
		return failures
	var seen: Dictionary[StringName, bool] = {}
	for index: int in pose_names.size():
		var pose := StringName(pose_names[index])
		if pose.is_empty():
			failures.append("pose %d has no name" % index)
		if seen.has(pose):
			failures.append("duplicate pose %s" % pose)
		seen[pose] = true
		if pose_scales[index] <= 0.0:
			failures.append("%s has a non-positive scale" % pose)
	return failures


func _rows() -> Dictionary[StringName, int]:
	if _index.size() != pose_names.size():
		_index.clear()
		for index: int in pose_names.size():
			_index[StringName(pose_names[index])] = index
	return _index
