class_name LayeredArenaVisual
extends ArenaVisual
## An Endless arena drawn as a scene of layers instead of one painting (ADR-0021).
##
## GameWorld shows it in place of the painted backdrop when the equipped arena has one
## ([member ArenaSkinData.visual_scene_path]). [method fit] lays it out for the screen: `%Backdrop`
## covers the view, and `%Group` (floor, board, doll, scythe, cloth, lanterns; one unit per texel,
## the floor's top-left at its origin) is scaled uniformly and placed under the HUD. The rect it
## returns is the floor exactly as drawn, and GameWorld takes the walls, enemy placement and dash
## collision from it, so play never leaves the painted floor. The scene is generated by its arena's
## packer; the motion is the arena's own script, which extends this one. Pausable; the arena
## stills its motion under Reduced Motion ([method set_reduced_motion]).

## Design pixels one texel covers at group scale 1: the pixel UI kit's grid.
const TEXEL: float = 4.0

## The floor in texels; `%Group`'s origin is its top-left corner.
@export var floor_texels: Vector2 = Vector2(152.0, 304.0)
## Everything the group draws, with the reach of its motion, in group texels.
@export var content_rect: Rect2 = Rect2()
## The top of the doll's head in group texels (negative: above the floor).
@export var head_top: float = 0.0
## Design pixels between the HUD's safe top and the head, so the HUD's bars stay clear of it.
@export var head_clear: float = 150.0
## Design pixels kept below the group.
@export var bottom_margin: float = 40.0
## Design pixels kept between the group and each side of the screen.
@export var side_margin: float = 12.0
## The group never grows past this scale: 1 keeps its texels on the 4-pixel grid of a 1080-wide
## phone.
@export var max_scale: float = 1.0

var _group_scale: float = 1.0

@onready var _group: Node2D = %Group
@onready var _backdrop: Node2D = %Backdrop
@onready var _backplate: Sprite2D = %Backplate


## Lays the arena out for a [param view_size] screen whose HUD starts [param safe_top] below its top,
## and returns the floor in the same coordinates (this node's, which are GameWorld's).
##
## The group is as big as the screen allows, up to [member max_scale]: its widest side
## [member side_margin] from the screen's edge, its head [member head_clear] under the HUD and its
## bottom [member bottom_margin] above the screen's. Spare height goes below it.
func fit(view_size: Vector2, safe_top: float) -> Rect2:
	var center: float = floor_texels.x * 0.5
	var half_width: float = maxf(center - content_rect.position.x, content_rect.end.x - center)
	var fit_width: float = (view_size.x * 0.5 - side_margin) / (half_width * TEXEL)
	var fit_height: float = (view_size.y - bottom_margin - safe_top - head_clear) / (
		(content_rect.end.y - head_top) * TEXEL
	)
	_group_scale = minf(max_scale, minf(fit_width, fit_height))
	var unit: float = TEXEL * _group_scale
	var origin := Vector2(
		roundf(view_size.x * 0.5 - center * unit), roundf(safe_top + head_clear - head_top * unit)
	)
	_group.position = origin
	_group.scale = Vector2(unit, unit)
	_floor_rect = Rect2(origin, floor_texels * unit)
	_fit_backdrop(view_size)
	_after_fit(view_size)
	return _floor_rect


## Scale of the centre group from the last [method fit]: 1 draws a texel as 4 design pixels.
func get_group_scale() -> float:
	return _group_scale


## Hook for the arena's script: lay out scenery that follows the screen rather than the group.
func _after_fit(_view_size: Vector2) -> void:
	pass


func _fit_backdrop(view_size: Vector2) -> void:
	if _backplate.texture == null:
		return
	var plate: Vector2 = _backplate.texture.get_size()
	var cover: float = maxf(
		(view_size.x + 2.0 * backdrop_overscan) / plate.x,
		(view_size.y + 2.0 * backdrop_overscan) / plate.y,
	)
	_backdrop.scale = Vector2(cover, cover)
	_backdrop.position = ((view_size - plate * cover) * 0.5).round()
