extends LayeredArenaVisual
## Stitchwarden's Vigil: the stitched doll holds the board up over the moonlit jungle (owner
## 2026-09-30).
##
## The scene is generated by concept_art/arenas_v2/stitchwarden_vigil/pack_vigil.py. The entire
## hood and face share a pivot and turn smoothly toward the Wisp. The scarf, shoulder strips and
## tunic move with the wind (`arena_hood_follow.gdshader`). The two long side cloth panels
## wave from a fixed root (`cloth_wave.gdshader`); separate scythe fire moves on its pixel grid
## and its light breathes; the lanterns flicker in place (`lantern_flicker.gdshader`); wisps drift
## and bats cross behind the board; the fog drifts low behind it. Nothing moves over the floor.
## Pausable with the run; Reduced Motion holds everything still.

## Largest whole-hood turn, in degrees, and how fast the rig follows the Wisp (per second).
const HEAD_TURN_DEGREES: float = 5.0
const HEAD_FOLLOW_RATE: float = 5.0
const HEAD_SHIFT_TEXELS := Vector2(2.0, 1.5)
## How far a lantern's light swings around the art's own brightness, and how fast.
const LANTERN_SWING: float = 0.18
const LANTERN_RATE: float = 6.0
## How far the flame's light breathes over its frames, and how fast.
const FLAME_SWING: float = 0.12
const FLAME_RATE: float = 5.0
## Texels the fog drifts either way, seconds per drift, and how far its opacity swings.
const FOG_DRIFT_TEXELS: float = 12.0
const FOG_PERIOD: float = 26.0
const FOG_ALPHA_SWING: float = 0.08
## Bats: seconds between two crossings, seconds a crossing takes, the band of the screen's height
## they fly in, and where the second bat trails the first (design px).
const BAT_WAIT_MIN: float = 9.0
const BAT_WAIT_MAX: float = 16.0
const BAT_CROSSING_SECONDS: float = 6.0
const BAT_BAND := Vector2(0.14, 0.24)
const BAT_TRAIL := Vector2(-34.0, 18.0)
## Design pixels the bats bob up and down as they cross.
const BAT_BOB: float = 10.0

var _time: float = 0.0
var _has_focus: bool = false
var _focus := Vector2.ZERO
var _head_turn: float = 0.0
var _head_home := Vector2.ZERO
var _head_shift := Vector2.ZERO
var _fog_home := Vector2.ZERO
var _fog_alpha: float = 1.0
var _view_size := Vector2.ZERO
var _bat_wait: float = 0.0
var _bat_age: float = -1.0
var _bat_from := Vector2.ZERO
var _bat_to := Vector2.ZERO
var _random := RandomNumberGenerator.new()
var _cloths: Array[Sprite2D] = []
var _lanterns: Array[Sprite2D] = []
var _wisps: Array[AnimatedSprite2D] = []
var _bats: Array[AnimatedSprite2D] = []

@onready var _head_rig: Node2D = %HeadRig
@onready var _body: Sprite2D = %Body
@onready var _flame: Sprite2D = %Flame
@onready var _fog: Sprite2D = %Fog
@onready var _wisp_layer: Node2D = %Wisps
@onready var _bat_layer: Node2D = %Bats


func _ready() -> void:
	_random.randomize()
	_head_home = _head_rig.position
	for child: Node in _group.get_children():
		if child is Sprite2D and String(child.name).begins_with("Cloth"):
			_cloths.append(child as Sprite2D)
		elif child is Sprite2D and String(child.name).begins_with("Lantern"):
			_lanterns.append(child as Sprite2D)
	for child: Node in _wisp_layer.get_children():
		if child is AnimatedSprite2D:
			_wisps.append(child as AnimatedSprite2D)
	for child: Node in _bat_layer.get_children():
		if child is AnimatedSprite2D:
			_bats.append(child as AnimatedSprite2D)
	_fog_home = _fog.position
	_fog_alpha = _fog.modulate.a
	_bat_wait = _random.randf_range(BAT_WAIT_MIN * 0.3, BAT_WAIT_MIN)
	_apply_reduced_motion()


func _process(delta: float) -> void:
	if _reduced_motion:
		return
	_time += delta
	_turn_head(delta)
	(_body.material as ShaderMaterial).set_shader_parameter(&"time_s", _time)
	for cloth: Sprite2D in _cloths:
		(cloth.material as ShaderMaterial).set_shader_parameter(&"time_s", _time)
	for lantern: Sprite2D in _lanterns:
		var phase: float = float(lantern.get_meta(&"phase", 0.0))
		var glow: float = 1.0 + LANTERN_SWING * _flicker(_time * LANTERN_RATE + phase)
		(lantern.material as ShaderMaterial).set_shader_parameter(&"glow", glow)
	var light: float = 1.0 + FLAME_SWING * _flicker(_time * FLAME_RATE)
	_flame.self_modulate = Color(light, light, light)
	(_flame.material as ShaderMaterial).set_shader_parameter(&"time_s", _time)
	for wisp: AnimatedSprite2D in _wisps:
		_place_wisp(wisp, _time)
	var drift: float = sin(TAU * _time / FOG_PERIOD)
	_fog.position = (_fog_home + Vector2(FOG_DRIFT_TEXELS * drift, 0.0)).round()
	_fog.modulate.a = _fog_alpha + FOG_ALPHA_SWING * sin(TAU * _time / (FOG_PERIOD * 0.7))
	_update_bats(delta)


func set_focus_point(point: Vector2) -> void:
	_focus = point
	_has_focus = true


func _after_fit(view_size: Vector2) -> void:
	_view_size = view_size
	for bat: AnimatedSprite2D in _bats:
		bat.scale = _backdrop.scale


func _apply_reduced_motion() -> void:
	_head_turn = 0.0
	_head_rig.rotation = 0.0
	_head_shift = Vector2.ZERO
	_head_rig.position = _head_home
	(_body.material as ShaderMaterial).set_shader_parameter(&"shift_texels", Vector2.ZERO)
	(_body.material as ShaderMaterial).set_shader_parameter(&"time_s", 0.0)
	for cloth: Sprite2D in _cloths:
		(cloth.material as ShaderMaterial).set_shader_parameter(&"time_s", 0.0)
		(cloth.material as ShaderMaterial).set_shader_parameter(&"motion_texels", Vector2.ZERO)
	for lantern: Sprite2D in _lanterns:
		(lantern.material as ShaderMaterial).set_shader_parameter(&"glow", 1.0)
	_flame.self_modulate = Color.WHITE
	(_flame.material as ShaderMaterial).set_shader_parameter(&"time_s", 0.0)
	_fog.position = _fog_home
	_fog.modulate.a = _fog_alpha
	for wisp: AnimatedSprite2D in _wisps:
		_place_wisp(wisp, 0.0)
	for sprite: AnimatedSprite2D in _wisps:
		if _reduced_motion:
			sprite.stop()
			sprite.frame = 0
		else:
			sprite.play()
	if _reduced_motion:
		_end_bat_crossing()


## Eases the hood and face together toward the Wisp on both screen axes.
func _turn_head(delta: float) -> void:
	var target: float = 0.0
	var target_shift := Vector2.ZERO
	if _has_focus and _view_size.x > 0.0:
		var head_x: float = _group.position.x + _head_home.x * _group.scale.x
		var head_y: float = _group.position.y + _head_home.y * _group.scale.y
		var side: float = clampf((_focus.x - head_x) / (_view_size.x * 0.5), -1.0, 1.0)
		var height: float = clampf((_focus.y - head_y) / (_view_size.y * 0.5), -1.0, 1.0)
		target = deg_to_rad(HEAD_TURN_DEGREES) * side
		target_shift = HEAD_SHIFT_TEXELS * Vector2(side, height)
	var follow: float = 1.0 - exp(-HEAD_FOLLOW_RATE * delta)
	_head_turn = lerpf(_head_turn, target, follow)
	_head_shift = _head_shift.lerp(target_shift, follow)
	_head_rig.rotation = _head_turn
	_head_rig.position = _head_home + _head_shift
	var cloth_response := _head_shift + Vector2(_head_turn * 12.0, 0.0)
	(_body.material as ShaderMaterial).set_shader_parameter(&"shift_texels", cloth_response)
	for cloth: Sprite2D in _cloths:
		(cloth.material as ShaderMaterial).set_shader_parameter(&"motion_texels", cloth_response)


## Puts a wisp on its loop (metadata `path` = centre x, centre y, x reach, y reach in group texels;
## `period` seconds; `phase`), on whole texels.
func _place_wisp(wisp: AnimatedSprite2D, time: float) -> void:
	var path: Vector4 = wisp.get_meta(&"path", Vector4.ZERO)
	var period: float = maxf(0.1, float(wisp.get_meta(&"period", 8.0)))
	var angle: float = TAU * time / period + float(wisp.get_meta(&"phase", 0.0))
	var centre := Vector2(path.x + path.z * sin(angle), path.y + path.w * sin(angle * 2.0) * 0.5)
	var frame_texture: Texture2D = wisp.sprite_frames.get_frame_texture(&"default", 0)
	var half: Vector2 = frame_texture.get_size() * 0.5 if frame_texture != null else Vector2.ZERO
	wisp.position = (centre - half).round()


## Waits, then flies the bats across the upper jungle, behind the doll and the board.
func _update_bats(delta: float) -> void:
	if _bats.is_empty() or _view_size.x <= 0.0:
		return
	if _bat_age < 0.0:
		_bat_wait -= delta
		if _bat_wait <= 0.0:
			_start_bat_crossing()
		return
	_bat_age += delta
	var progress: float = _bat_age / BAT_CROSSING_SECONDS
	if progress >= 1.0:
		_end_bat_crossing()
		return
	var point: Vector2 = _bat_from.lerp(_bat_to, progress)
	point.y += BAT_BOB * sin(progress * TAU * 1.5)
	for index: int in _bats.size():
		var trail: Vector2 = BAT_TRAIL * float(index)
		if _bat_to.x < _bat_from.x:
			trail.x = -trail.x
		_bats[index].position = (point + trail).round()


func _start_bat_crossing() -> void:
	var margin: float = 60.0
	var leftwards: bool = _random.randf() < 0.5
	var y: float = _view_size.y * _random.randf_range(BAT_BAND.x, BAT_BAND.y)
	var drift: float = _view_size.y * _random.randf_range(-0.04, 0.04)
	_bat_from = Vector2(_view_size.x + margin if leftwards else -margin, y)
	_bat_to = Vector2(-margin if leftwards else _view_size.x + margin, y + drift)
	_bat_age = 0.0
	for bat: AnimatedSprite2D in _bats:
		bat.flip_h = leftwards
		bat.visible = true
		bat.play()


func _end_bat_crossing() -> void:
	_bat_age = -1.0
	_bat_wait = _random.randf_range(BAT_WAIT_MIN, BAT_WAIT_MAX)
	for bat: AnimatedSprite2D in _bats:
		bat.visible = false
		bat.stop()


## A smooth, irregular swing in -1..1 for light that flickers.
func _flicker(t: float) -> float:
	return 0.6 * sin(t) + 0.3 * sin(t * 2.7 + 1.3) + 0.1 * sin(t * 7.1 + 0.4)
