class_name WholeFrameCharacterVisual
extends PlayableCharacterVisual
## A whole-frame sprite character on one [AnimatedSprite2D].
##
## The shared behaviour for every character built to
## [url=res://docs/guides/character_sprite_frames.md]the whole-frame contract[/url] rather than as a
## bone rig. This script never steps frames by hand: it decides which animation should be playing,
## which way up the body is drawn, and which of the two frame sets is in memory.
## [PlayableCharacterVisual] still owns the state machine, heading, alpha and the squash on a state
## change.
##
## A character subclasses this only to carry a `class_name` the tests and fixtures can type against;
## everything that differs between characters is the two frame-set paths, set per scene.
##
## [b]Five animations, and no more[/b] (owner, 2026-09-20). The controller still speaks the full
## thirteen-state vocabulary in [PlayableCharacterVisual] — the bone rigs animate all of it for
## free — but a drawn character only has frames for what the player actually looks at:
##
## [codeblock]
## dash_loop                      the dash, which IS the attack
## wall_bottom / _top / _left     resting against a wall (_right is _left mirrored)
## storefront_idle                Home and the Shop card
## [/codeblock]
##
## Everything else resolves onto one of those in [method _target_animation]: a windup shows only the
## aim arrow, a landing is the wall animation arriving, a hit is the controller's blink and edge
## reset, and a death is the controller's alpha dissolve over whatever was showing. The frames that
## used to carry those beats (`dash_start`, `dash_end`, `attack`, `move_fly`, `hit_reaction`,
## `death`, `revive_spawn`, `victory`, the gameplay `idle_hover` and the two menu reactions) are
## still in `concept_art/`, so restoring any of them is a row in the packer and a re-pack.
##
## Three things are specific to a whole-frame character:
##
## 1. **Two frame sets, never both.** A Shop card holds a live character, and a texture costs its
##    full uncompressed size in VRAM whatever it cost on disk, so the menu animation and the
##    gameplay animations are separate resources, [method load]ed on demand. A run never holds the
##    storefront sheet and a menu never holds the run sheet.
## 2. **The wall frames are painted in screen space** — upright to the player on every surface — so
##    while one shows, the rotation the base applies to stand on that wall is cancelled again.
##    `wall_right` is `wall_left` mirrored, which is free and keeps eight frames off the sheet.
## 3. **The frames carry their own motion.** The pack already paints the breath, the flame drift and
##    the leaf overlap, so `bounce_amount` is 0: adding the shared bob on top would read as two
##    different rhythms fighting.
##
## **A menu may play a video instead** (ADR-0016). With [member menu_video] set, Home and the Shop
## card play a pre-rendered clip in place of `storefront_idle`, and a menu then loads no frame set
## at all. Under Reduced Motion the sprite loop's first frame is held instead, as for every other
## character, so a video is never the only way a character can appear.

## The two generated frame sets, set per character in its scene. Deliberately paths and not
## `preload`: see the class doc.
@export_file("*.tres") var gameplay_frames: String = ""
@export_file("*.tres") var menu_frames: String = ""

## The dash. The dash *is* the attack, so there is no separate contact animation: one of these
## frames is the contact frame and the accent holds the same picture.
const DASH: StringName = &"dash_loop"
const WALL_BOTTOM: StringName = &"wall_bottom"
const WALL_TOP: StringName = &"wall_top"
const WALL_LEFT: StringName = &"wall_left"
## Screen-space animations: while one plays, the body is turned back upright.
const SURFACE_ANIMATIONS: Array[StringName] = [WALL_BOTTOM, WALL_TOP, WALL_LEFT]
## Inward wall normal (see [member surface_normal]) to the animation painted for that wall, and
## whether it is drawn mirrored. The right wall is the left wall flipped.
const SURFACE_NORMAL_ANIMATIONS: Dictionary[Vector2, Array] = {
	Vector2.UP: [WALL_BOTTOM, false],
	Vector2.DOWN: [WALL_TOP, false],
	Vector2.RIGHT: [WALL_LEFT, false],
	Vector2.LEFT: [WALL_LEFT, true],
}

## Gameplay states drawn with the dash frames: the launch, the flight and the kill accent are one
## picture. Every other state falls through to the wall the character is resting against.
const DASH_STATES: Array[StringName] = [DASH_START, DASH_LOOP, ATTACK]

## The one menu animation. A card that is focused, equipped or bought keeps breathing — the
## storefront reactions were cut with the rest (owner, 2026-09-20).
@export var menu_idle_animation: StringName = &"storefront_idle"
const MENU_IDLE: StringName = &"storefront_idle"
## The menu performance as a pre-rendered video, generated by `tools/art/extract_menu_video.py`;
## null performs [member menu_idle_animation] from the menu frame set.
@export var menu_video: MenuVideoData
## What [method get_current_animation] reports while the menu video is on screen.
const MENU_VIDEO: StringName = &"menu_video"

## The menu frames are a 448 px cell where a run uses 384, so they are drawn at 384/448 to keep the
## character the same apparent height on a Shop card as in a run.
const MENU_SCALE: float = 384.0 / 448.0
## Radians per second the body rights itself when a screen-space wall animation takes over. Fast
## enough to look immediate, slow enough that landing under a ceiling never spins in one frame
## (the rig smoothness contract measures exactly that).
const BODY_TURN_RATE: float = 24.0
## The frame Reduced Motion holds for each animation; every other one holds its first. The dash
## holds its contact frame, which is the one the player reads a kill from.
const REDUCED_FRAMES: Dictionary[StringName, int] = {
	DASH: 2,
}

var _animation: StringName = &""
var _menu: bool = false
var _still: bool = false
## Which frame set is loaded, so switching costs nothing when nothing changed.
var _frames_path: String = ""
## The menu video while one is on screen; freed as soon as the character leaves the menu.
var _video: CharacterMenuVideo

@onready var _body: Node2D = %Body
@onready var _sprite: AnimatedSprite2D = %PoseSprite


func _ready() -> void:
	super()
	# A Shop card is configured before it is added to the tree, so `set_preview_mode` and
	# `set_reduced_motion` can both land ahead of `_ready`. Re-apply what they asked for now that
	# the sprite exists, or every card would show the gameplay frames.
	_apply_frame_set()
	_refresh(0.0, true)


## Menu previews perform the storefront loop: a menu character is not resting against anything, so
## the wall animations are never reachable there.
func set_preview_mode(enabled: bool) -> void:
	_menu = enabled
	super(enabled)
	_apply_frame_set()
	_refresh(0.0, true)


## Reduced Motion holds one readable frame per animation instead of playing it, and stops the walls
## turning; the state and the wall it picks are unchanged.
func set_reduced_motion(enabled: bool) -> void:
	_still = enabled
	super(enabled)
	_apply_frame_set()
	_refresh(0.0, true)


## The animation on screen, for the tests and the QA fixtures.
func get_current_animation() -> StringName:
	return _animation


## True while the menu frame set is the one in memory. The tests assert a run never holds it.
func is_menu_frame_set() -> bool:
	return _frames_path == menu_frames


## True while the menu video is on screen and playing.
func is_menu_video_playing() -> bool:
	return _video != null and _video.is_playing() and not _video.paused


## The menu video player while one is on screen, for the tests and the QA fixtures.
func get_menu_video_player() -> VideoStreamPlayer:
	return _video


## True while the character is drawn mirrored — the right wall, which reuses the left wall's frames.
func is_mirrored() -> bool:
	return _sprite.flip_h


## Box around the current frame in this rig's frame. The base walks sprite layers; this rig has one
## [AnimatedSprite2D] instead.
func get_layer_bounds() -> Rect2:
	var rect := Rect2()
	if _video != null:
		rect = Rect2(_video.position, _video.size)
	else:
		var texture: Texture2D = _current_texture()
		if texture == null:
			return Rect2()
		var size: Vector2 = texture.get_size() * _sprite.scale
		rect = Rect2(-size * 0.5, size)
	var to_rig: Transform2D = (
		get_global_transform().affine_inverse() * _body.get_global_transform()
	)
	var bounds := Rect2(to_rig * rect.position, Vector2.ZERO)
	for corner: Vector2 in [
		Vector2(rect.end.x, rect.position.y), rect.end, Vector2(rect.position.x, rect.end.y),
	]:
		bounds = bounds.expand(to_rig * corner)
	return bounds


func _update_secondary_motion(delta: float) -> void:
	_refresh(delta, false)


## A new state starts its animation at once, but lets the wall counter-rotation ease in.
func _on_state_started(_state_name: StringName) -> void:
	if not is_node_ready():
		return
	_refresh(0.0, false)


func _apply_reduced_pose() -> void:
	_refresh(0.0, true)


## Picks the animation, points the body the right way up and keeps the drawn size honest.
func _refresh(delta: float, snap: bool) -> void:
	if not is_node_ready():
		return
	if _video != null:
		_animation = MENU_VIDEO
		_body.rotation = 0.0
		return
	var wanted: StringName = _target_animation()
	var mirrored: bool = _menu == false and _mirrors(wanted)
	if wanted != _animation or mirrored != _sprite.flip_h:
		_animation = wanted
		_sprite.flip_h = mirrored
		_sprite.animation = wanted
		_sprite.frame = REDUCED_FRAMES.get(wanted, 0) if _still else 0
	_sprite.scale = Vector2.ONE * (MENU_SCALE if _menu else 1.0)
	if _still:
		_sprite.pause()
	elif not _sprite.is_playing():
		_sprite.play()
	# A screen-space frame is already drawn the way the player must see it, so the rotation the base
	# applied to stand on this wall is taken off again instead of turning the picture twice.
	var inherited: float = wrapf(_body.global_rotation - _body.rotation, -PI, PI)
	var upright: float = -inherited if _animation in SURFACE_ANIMATIONS else 0.0
	if snap or _still:
		_body.rotation = upright
	else:
		_body.rotation = rotate_toward(_body.rotation, upright, delta * BODY_TURN_RATE)


## The whole thirteen-state vocabulary, resolved onto the five animations a drawn character has.
##
## A menu character always performs the storefront loop. In a run the character is either dashing or
## against a wall: there is nothing else it can be doing, because the windup shows only the aim
## arrow, the landing *is* the wall animation arriving, and a hit or a death plays out through the
## controller's blink, edge reset and alpha dissolve over whatever is already on screen.
func _target_animation() -> StringName:
	if _menu:
		return menu_idle_animation
	var state: StringName = get_current_visual_state()
	# Owner decision 2026-09-19: holding the aim arrow must not change the character at all. Nothing
	# in a run asks for it; if anything ever does, whatever is already playing keeps playing.
	if state == AIM_CHARGE:
		return _animation if _animation != &"" else _nearest_wall()[0]
	if state in DASH_STATES:
		return DASH
	return _nearest_wall()[0]


func _mirrors(animation: StringName) -> bool:
	return animation == WALL_LEFT and bool(_nearest_wall()[1])


## The arena is a rounded polygon, so a resting normal is rarely exactly cardinal: the nearest wall
## by alignment is the right answer, not the one that happens to round.
func _nearest_wall() -> Array:
	var best: Array = SURFACE_NORMAL_ANIMATIONS[Vector2.UP]
	var closest: float = -INF
	for normal: Vector2 in SURFACE_NORMAL_ANIMATIONS:
		var alignment: float = normal.dot(surface_normal)
		if alignment > closest:
			closest = alignment
			best = SURFACE_NORMAL_ANIMATIONS[normal]
	return best


## Swaps the loaded frame set. Only one is ever in memory: a Shop card must not pay for the run
## animations of every character on the carousel.
##
## A menu with a video holds no frame set at all, so a Shop card playing a clip pays for neither
## sheet. Reduced Motion falls back to the menu frame set, which holds one readable frame.
func _apply_frame_set() -> void:
	if not is_node_ready():
		return
	var video: bool = _plays_menu_video()
	var wanted: String = "" if video else (menu_frames if _menu else gameplay_frames)
	if _frames_path != wanted:
		_frames_path = wanted
		_sprite.sprite_frames = null if wanted.is_empty() else load(wanted) as SpriteFrames
		_animation = &""
	_sprite.visible = not video
	if video:
		_start_menu_video()
	else:
		_stop_menu_video()


func _plays_menu_video() -> bool:
	return _menu and not _still and menu_video != null and menu_video.stream != null


## Adds the shared [CharacterMenuVideo]; it plays, pauses while hidden and restarts after its screen
## is re-attached on its own.
func _start_menu_video() -> void:
	if _video != null:
		return
	_video = CharacterMenuVideo.create(menu_video)
	_body.add_child(_video)


func _stop_menu_video() -> void:
	if _video == null:
		return
	_video.dispose()
	_video = null


func _current_texture() -> Texture2D:
	var frames: SpriteFrames = _sprite.sprite_frames
	if frames == null or not frames.has_animation(_sprite.animation):
		return null
	return frames.get_frame_texture(_sprite.animation, _sprite.frame)
